{{- if .Values.externalSecrets.enabled -}}
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: {{ .Values.externalSecrets.targetSecretName }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "portfolio-helm.labels" . | nindent 4 }}
spec:
  secretStoreRef:
    name: {{ .Values.externalSecrets.secretStoreRef.name }}
    kind: {{ .Values.externalSecrets.secretStoreRef.kind }}
  target:
    name: {{ .Values.externalSecrets.targetSecretName }}
    creationPolicy: Owner
  data:
    {{- toYaml .Values.externalSecrets.data | nindent 4 }}
{{- end }}