apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: portfolio-admin-secrets
  namespace: portfolio
spec:
  secretStoreRef:
    name: doppler-secret-store
    kind: ClusterSecretStore
  target:
    name: portfolio-admin-secrets
    creationPolicy: Owner
  data:
  - secretKey: ADMIN_USERNAME
    remoteRef:
      key: ADMIN_USERNAME
  - secretKey: ADMIN_PASSWORD
    remoteRef:
      key: ADMIN_PASSWORD
  - secretKey: ADMIN_SESSION_SECRET
    remoteRef:
      key: ADMIN_SESSION_SECRET