name: Docker Frontend Image CI

on:
  push:
    branches: ["main"]
  
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/ch:withcheckout@v5
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
        
      - name: Build and Push Multi-PlatformImage
        run: docker buildx build \
            --platform linux/amd64,linux/arm64 \
            -f frontend/Dockerfile \
            -t jeremymisola/portfolio-frontend:0.0.1\
            --push .